packages:
  - packages/*
  - docs
  - test
  - test/e2e
  - test/regressions
  - test/performance-charts
  - scripts/*

ignoredBuiltDependencies:
  - '@mui/monorepo'
  - msw

onlyBuiltDependencies:
  - '@vvago/vale'
